### ISSUE TITLE
casual model?

### ISSUE THREAD

**Issue by Chengyo** [deepnetni/msa-dpcrn#1]
很棒的工作，想请问是因果模型吗？因为AFF_BLK模块输入维度写的是B,F,T,C，并且使用了LayerNorm，训练数据文章里写的长度为10s，请问下这里是否采取了一些额外措施保证模型的因果性呢？
![image](https://github.com/user-attachments/assets/423508b7-6e99-411c-ab6b-af066dc06f92)

**Comment by deepnetni** [comment]
是因果的模型，这里进出 layerNorm 都会做 permute 让 F 为最后一个维度，然后只在频率维度做 normalization，避免引入时间维度；

**Comment by Chengyo** [comment]
感谢解答
